apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: tcp-service
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    opentelemetry.io/name: frontend-proxy
